# Generated by Django 4.0.2 on 2022-02-16 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="QuestionCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, verbose_name="Question Category Name"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question_text",
                    models.CharField(max_length=50, verbose_name="Question Text"),
                ),
                (
                    "question_category",
                    models.ManyToManyField(
                        related_name="categories", to="bot.QuestionCategory"
                    ),
                ),
            ],
            options={"verbose_name": "Question", "verbose_name_plural": "Questions",},
        ),
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "answer_text",
                    models.CharField(max_length=50, verbose_name="Answer Text"),
                ),
                (
                    "question",
                    models.ManyToManyField(related_name="questions", to="bot.Question"),
                ),
            ],
            options={"verbose_name": "Answer", "verbose_name_plural": "Answers",},
        ),
    ]
