# Generated by Django 4.0.2 on 2022-02-16 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questioncategory',
            options={'verbose_name': 'Question Category', 'verbose_name_plural': 'Question Categories'},
        ),
    ]
