POST http://localhost:5055/sockect.io
content-type: application/json

{
  "sender": "user_uttered",
  "message": "Hi there!",
}

###
GET http://localhost:5005/

###
GET http://localhost:5055/sockect.io