# Generated by Django 4.0.2 on 2022-03-04 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('university', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDegree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.IntegerField(verbose_name='Degree')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.course', verbose_name='Course')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.faculty', verbose_name='Faculty')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.student', verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Student Degree',
                'verbose_name_plural': 'Students Degrees',
            },
        ),
    ]
