# Generated by Django 4.0.2 on 2022-03-07 07:19

from django.db import migrations, models
import university.models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0003_studentdegree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdegree',
            name='degree',
            field=models.IntegerField(validators=[university.models.validate_degree], verbose_name='Degree'),
        ),
    ]
