# Generated by Django 4.0.2 on 2022-03-12 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0004_alter_studentdegree_degree'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='class_date',
        ),
        migrations.RemoveField(
            model_name='course',
            name='prev_course',
        ),
        migrations.AddField(
            model_name='class',
            name='claas_day',
            field=models.CharField(choices=[('  Mo', 'Monday'), ('Tu', 'Tuesday'), ('We', 'Wednesday'), ('Th', 'Thursday'), ('Fr', 'Friday'), ('Sa', 'Saturday'), ('Su', 'Sunday')], default='Su', max_length=10, verbose_name='Class Day'),
        ),
        migrations.AddField(
            model_name='class',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Class end time'),
        ),
        migrations.AddField(
            model_name='class',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Class start time'),
        ),
        migrations.AddField(
            model_name='course',
            name='num',
            field=models.CharField(default=0, max_length=50, verbose_name='Course Number'),
        ),
        migrations.CreateModel(
            name='PreCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course', to='university.course', verbose_name='Course')),
                ('prev_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_course', to='university.course', verbose_name='Previous Course')),
            ],
            options={
                'verbose_name': 'Previous Course',
                'verbose_name_plural': 'Previous Courses',
            },
        ),
    ]
